sequenceDiagram

    actor User
    actor Scooter

    User ->> ScooterApp: register(user)
    alt User already registered
        ScooterApp -->> User: Already Registered!
    else
        activate ScooterApp
        ScooterApp -->> User: User registered
        deactivate ScooterApp
    end
    alt User is under 17
        ScooterApp -->> User: Too young to register!
    else
        activate ScooterApp
        ScooterApp -->> User: User registered
        deactivate ScooterApp
    end

    User ->> ScooterApp: Rent Scooter
    ScooterApp ->> Scooter: rent()
    alt Scooter is either broken or on low battery
        Scooter -->> ScooterApp: Scooter Unavailable
    else
        activate Scooter
        Scooter -->> ScooterApp: Ride Began
        ScooterApp -->> User: Enjoy the ride
    end

    User ->> ScooterApp: Dock Scooter
    ScooterApp ->> Scooter: dock(station)
    alt No station passed in
        Scooter -->> ScooterApp: Needs station argument
    else
        deactivate Scooter
        Scooter -->> ScooterApp: Successfully docked
        ScooterApp -->> User: Scooter docked
    end

    User ->> ScooterApp: Login
    activate ScooterApp
    alt User in registered users
        ScooterApp -->> User: User in registered users
    else
        ScooterApp -->> User: User not in registered users
    end
    alt Username or password is correct
        ScooterApp -->> User: Login successful
    else
        ScooterApp -->> User: Username or password is incorrect
    end
    deactivate ScooterApp

    User ->> ScooterApp: Add Scooter addScooter(location, scooter)
    activate ScooterApp
    ScooterApp ->> User: Scooter Added
    deactivate ScooterApp

    User ->> ScooterApp: Remove Scooter removeScooter(scooterToRemove)
    activate ScooterApp
    alt Serial Number of Scooter Not Found
        ScooterApp ->> User: Scooter not found
    else
        ScooterApp ->> Scooter: Please remove yourself
        Scooter -->> ScooterApp: Removed
        ScooterApp -->> User: Scooter successfully removed
    deactivate ScooterApp
    end
