flowchart LR
    EXISTINGUSER([Existing User])
    NEWUSER([New User])
    SCOOTER([Scooter])
    REPAIRSERVICE([Repair Service])
    style REPAIRSERVICE fill:#ccf
    style SCOOTER fill:#ccf
    style NEWUSER fill:#ccf
    style EXISTINGUSER fill:#ccf
    EXISTINGUSER-->login[Login]
    EXISTINGUSER-->rent
    EXISTINGUSER-->dock
    NEWUSER-->register
    EXISTINGUSER-->requestRepair
    EXISTINGUSER-->addScooter
    SCOOTERAPP([ScooterApp])
    style SCOOTERAPP fill:#ccf
    EXISTINGUSER-->removeScooter


    addScooter[addScooter]
    removeScooter[removeScooter]

    rent[rent]



    dock[dock]



    register[Register]

    login-->SCOOTERAPP
    register-->SCOOTERAPP
    requestRepair-->SCOOTERAPP
    register-->EXISTINGUSER
    rent-->SCOOTER
    dock-->SCOOTER
    SCOOTER<-->SCOOTERAPP

    SCOOTERAPP<-->REPAIRSERVICE

    addScooter-->SCOOTERAPP
    removeScooter-->SCOOTERAPP

    register
